### ISSUE TITLE
Model changes upon relogging.

### ISSUE THREAD

**Issue by MagmaSlime123** [KAMKEEL/MorePlayerModels-Plus#4]
Title. Relogging causes your current model to randomly change.

Happens with/without other mods, and in the original MPM mod.
Might be caused by LOTR, and the MPM LOTR addon should just be built into MPM Plus itself, which might even fix other issues.

MPM/MPM Plus also has other minor issues with LOTR mobs as well. I will open new issues for those, if wanted.

https://user-images.githubusercontent.com/51277766/204066713-8c1bd046-3f00-4232-96fa-75eedfa2cd41.mp4

**Comment by KAMKEEL** [comment]
After investigating this issue, it seems the data for an Entity in LOTR, specifically, their Texture is selected at _random_. This is an issue because whenever you refresh your Entity in MPM+ a new texture will be chosen because, for an Entity in LOTR, it is **not** constant. 

Upon reconnecting, you're actually not changing EntityModels, you're changing the texture and if the texture does include body parts like breasts then it renders blank. So the model you have, simple has different textures that includes different parts.


As seen in LOTR Code, the Entity Texture is fully random- If you go into MPM+, select an LOTR Hobbit and then go to _EXTRAS_. Change any of the LOTR Entity Fields and it will randomize the skin again.

<https://github.com/Hummel009/The-Lord-of-the-Rings/blob/eb3b9d96a8ac7e34378a24413a6c8267ad764bb1/src/main/java/lotr/client/render/entity/LOTRRenderHobbit.java#L40> 

Sorry, but I will mark this as `closed` and `help wanted` because I am not willing to mess around with their own entity saving.
